#!/usr/bin/env bash
# MPF PostToolUse hook for Write/Edit tools.
# Generated by adapters/claude-code/generate.sh from core/hooks/doc-update-hook.md

INPUT="$1"

FILE_PATH=$(echo "$INPUT" | sed -n 's/.*"file_path"[[:space:]]*:[[:space:]]*"\([^"]*\)".*/\1/p' | head -1)

if [ -z "$FILE_PATH" ]; then
  exit 0
fi

case "$FILE_PATH" in
  */docs/*|*/.claude/*|*/archive/*|*.md|*.json|*.yml|*.yaml|*.toml|*.lock|*.env*)
    exit 0
    ;;
esac

echo "[MPF] Source file modified: $FILE_PATH"
echo "[MPF] Check if docs/technical-specs/code-atlas.md, code-modules/, or PROJECT_STATUS.md need updating."
